import {ArrowRight,Gift,Minus,Plus,ShoppingBag,Trash2} from 'lucide-react'
import {useState} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {useCart} from '../context/CartContext'
import {api} from '../services/api'
export default function Cart(){const{cart,update,remove,refresh}=useCart();const[checkout,setCheckout]=useState(false);const[form,setForm]=useState({shipping_name:'',shipping_phone:'',shipping_address:'',payment_method:'cod',coupon_code:'',gift_note:''});const[error,setError]=useState('');const nav=useNavigate();const shipping=Number(cart.subtotal)>=1499?0:99
 async function placeOrder(e:React.FormEvent){e.preventDefault();setError('');try{const order=await api<{order_number:string}>('/orders/checkout',{method:'POST',body:JSON.stringify({...form,coupon_code:form.coupon_code||null})});await refresh();nav(`/orders?placed=${order.order_number}`)}catch(err){setError(err instanceof Error?err.message:'Checkout failed')}}
 if(!cart.items.length)return <section className="empty-state"><ShoppingBag/><h1>Your boutique bag is empty</h1><p>Explore curated dresses and select your preferred size and colour.</p><Link className="btn" to="/products">Shop the collection <ArrowRight/></Link></section>
 return <section className="cart-page"><div><span className="eyebrow">Your selection</span><h1>Boutique bag</h1><div className="cart-list">{cart.items.map(item=><article key={item.id}><img src={item.product.image_url}/><div className="cart-copy"><h3>{item.product.title}</h3><p>{item.product.brand}</p><div className="variant-line"><span>Size {item.variant.size}</span><span>{item.variant.color}</span></div><strong>₹{Number(item.unit_price).toLocaleString()}</strong></div><div className="qty"><button onClick={()=>item.quantity>1&&update(item.id,item.quantity-1)}><Minus/></button><b>{item.quantity}</b><button onClick={()=>update(item.id,item.quantity+1)}><Plus/></button></div><b className="line-total">₹{Number(item.line_total).toLocaleString()}</b><button className="trash" onClick={()=>remove(item.id)}><Trash2/></button></article>)}</div></div><aside className="order-summary"><h2>Order summary</h2><div><span>Subtotal</span><b>₹{Number(cart.subtotal).toLocaleString()}</b></div><div><span>Delivery</span><b>{shipping?'₹99':'Complimentary'}</b></div><hr/><div className="summary-total"><span>Total</span><b>₹{(Number(cart.subtotal)+shipping).toLocaleString()}</b></div>{!checkout?<button className="btn full" onClick={()=>setCheckout(true)}>Continue to secure checkout</button>:<form className="checkout-form" onSubmit={placeOrder}><label>Name<input required value={form.shipping_name} onChange={e=>setForm({...form,shipping_name:e.target.value})}/></label><label>Phone<input required value={form.shipping_phone} onChange={e=>setForm({...form,shipping_phone:e.target.value})}/></label><label>Delivery address<textarea required value={form.shipping_address} onChange={e=>setForm({...form,shipping_address:e.target.value})}/></label><label>Payment<select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}><option value="cod">Cash on delivery</option><option value="mock_card">Mock secure card</option></select></label><label>Coupon<input placeholder="WELCOME15" value={form.coupon_code} onChange={e=>setForm({...form,coupon_code:e.target.value.toUpperCase()})}/></label><label><span className="gift-label"><Gift/> Gift note</span><textarea placeholder="Optional message" value={form.gift_note} onChange={e=>setForm({...form,gift_note:e.target.value})}/></label>{error&&<div className="form-error">{error}</div>}<button className="btn full">Place order</button></form>}<p className="secure-text">Secure checkout · Size-level inventory · Easy order tracking</p></aside></section>
}
