import {Search,SlidersHorizontal} from 'lucide-react'
import {useEffect,useState} from 'react'
import {useSearchParams} from 'react-router-dom'
import ProductCard from '../components/ProductCard'
import {api} from '../services/api'
import type {Category,Product} from '../types'
export default function Catalog(){const[params,setParams]=useSearchParams();const[products,setProducts]=useState<Product[]>([]);const[categories,setCategories]=useState<Category[]>([]);const[total,setTotal]=useState(0);const[loading,setLoading]=useState(true);const query=params.toString()
 useEffect(()=>{setLoading(true);Promise.all([api<{items:Product[];total:number}>(`/products?${query}`),api<Category[]>('/categories')]).then(([b,c])=>{setProducts(b.items);setTotal(b.total);setCategories(c)}).finally(()=>setLoading(false))},[query])
 const update=(key:string,value:string)=>{const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);setParams(next)}
 return <section className="catalog-page"><div className="catalog-title"><span className="eyebrow">The boutique collection</span><h1>Find a style made for your moment</h1><p>{total} curated designs with real-time size and colour availability.</p></div><div className="catalog-toolbar fashion-toolbar"><label className="search-box"><Search/><input value={params.get('q')||''} onChange={e=>update('q',e.target.value)} placeholder="Search dress, fabric, brand or occasion"/></label><select value={params.get('category')||''} onChange={e=>update('category',e.target.value)}><option value="">All collections</option>{categories.map(c=><option key={c.id} value={c.slug}>{c.name}</option>)}</select><select value={params.get('size')||''} onChange={e=>update('size',e.target.value)}><option value="">All sizes</option>{['XS','S','M','L','XL','XXL','Free Size'].map(size=><option key={size}>{size}</option>)}</select><select value={params.get('sort')||'newest'} onChange={e=>update('sort',e.target.value)}><option value="newest">Newest edit</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option><option value="title">Name A–Z</option></select><button className="filter-button"><SlidersHorizontal/> More filters</button></div>{loading?<div className="loading">Loading collection…</div>:products.length?<div className="product-grid catalog-grid">{products.map(product=><ProductCard key={product.id} product={product}/>)}</div>:<div className="empty-state inline"><h2>No styles found</h2><p>Try another size, collection or search term.</p></div>}</section>
}
