import {Minus,Plus,RefreshCcw,Ruler,ShieldCheck,ShoppingBag,Star,Truck} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {useNavigate,useParams} from 'react-router-dom'
import {useAuth} from '../context/AuthContext'
import {useCart} from '../context/CartContext'
import {api} from '../services/api'
import type {Product,Variant} from '../types'
export default function ProductDetail(){const{slug}=useParams();const[product,setProduct]=useState<Product|null>(null);const[selected,setSelected]=useState<Variant|null>(null);const[qty,setQty]=useState(1);const{user}=useAuth();const{add}=useCart();const nav=useNavigate();useEffect(()=>{api<Product>(`/products/${slug}`).then(item=>{setProduct(item);setSelected(item.variants.find(v=>v.stock>0&&v.is_active)||null)})},[slug]);const colors=useMemo(()=>product?[...new Set(product.variants.filter(v=>v.stock>0&&v.is_active).map(v=>v.color))]:[],[product]);if(!product)return <div className="loading">Loading style…</div>
 const sizes=[...new Set(product.variants.filter(v=>v.stock>0&&v.is_active&&(!selected||v.color===selected.color)).map(v=>v.size))]
 function pickColor(color:string){setSelected(product!.variants.find(v=>v.color===color&&v.stock>0&&v.is_active)||null);setQty(1)}
 function pickSize(size:string){const color=selected?.color||colors[0];setSelected(product!.variants.find(v=>v.size===size&&v.color===color&&v.stock>0&&v.is_active)||null);setQty(1)}
 async function addToCart(){if(!user){nav('/login');return}if(!selected)return;await add(product!.id,selected.id,qty);nav('/cart')}
 const price=Number(product.price)+Number(selected?.additional_price||0);const gallery=[product.image_url,...product.gallery_urls.split(',').map(v=>v.trim()).filter(Boolean)]
 return <section className="detail-page boutique-detail"><div className="detail-gallery"><div className="detail-cover"><img src={gallery[0]} alt={product.title}/><span>{product.category.name}</span></div>{gallery[1]&&<div className="detail-secondary"><img src={gallery[1]} alt={`${product.title} alternate`}/></div>}</div><div className="detail-content"><span className="eyebrow">{product.vendor}</span><h1>{product.title}</h1><p className="detail-brand">Designed by <b>{product.brand}</b> · {product.occasion}</p><div className="detail-rating"><Star fill="currentColor"/><b>{product.average_rating||'New'}</b><span>{product.review_count} verified reviews</span></div><div className="detail-price"><strong>₹{price.toLocaleString()}</strong>{product.compare_at_price&&<del>₹{Number(product.compare_at_price).toLocaleString()}</del>}<small>Inclusive of all taxes</small></div><p className="description">{product.description}</p><div className="option-block"><div><b>Colour</b><span>{selected?.color||'Select'}</span></div><div className="color-options">{colors.map(color=><button className={selected?.color===color?'active':''} key={color} onClick={()=>pickColor(color)}>{color}</button>)}</div></div><div className="option-block"><div><b>Select size</b><button className="size-guide"><Ruler/> Size guide</button></div><div className="size-options">{sizes.map(size=><button className={selected?.size===size?'active':''} key={size} onClick={()=>pickSize(size)}>{size}</button>)}</div>{selected&&<small>{selected.stock} pieces available in this option</small>}</div><div className="metadata fashion-meta"><span><b>Fabric</b>{product.fabric}</span><span><b>Fit</b>{product.fit}</span><span><b>Care</b>{product.care_instructions}</span><span><b>Style SKU</b>{selected?.sku||product.sku}</span></div><div className="buy-row"><div className="qty"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button><b>{qty}</b><button onClick={()=>setQty(Math.min(selected?.stock||1,qty+1))}><Plus/></button></div><button className="btn buy-button" disabled={!selected} onClick={addToCart}><ShoppingBag/> Add selected style</button></div><div className="delivery-notes"><span><Truck/><div><b>Fast boutique delivery</b><small>Dispatches in 1–2 business days</small></div></span><span><RefreshCcw/><div><b>Easy size exchange</b><small>Eligible unworn styles within 7 days</small></div></span><span><ShieldCheck/><div><b>Protected purchase</b><small>Server-validated pricing and inventory</small></div></span></div></div></section>
}
